version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: "my_app_backend"
    restart: always
    volumes:
      - ./app/load:/app/load
    ports:
      - "8000:8000"
    networks:
      - nebula-net


  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: "my_app_frontend"
    restart: always
    ports:
      - "8501:8501"
    networks:
      - nebula-net


  redis:
    image: "redis:alpine"
    container_name: "my_app_redis"
    restart: always
    networks:
      - nebula-net

  nginx:
    image: jonasal/nginx-certbot
    container_name: my_app_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CERTBOT_EMAIL=sanderchernitsky@gmail.com
      - CERTBOT_DOMAINS=loop.in.net
      - STAGING=0  # 1=test mode, 0=real
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - nebula-net

networks:
  nebula-net:
    driver: bridge

