FROM python:3.10-slim AS backend
ENV PYTHONPATH=/app
WORKDIR /app
COPY requirements.txt .
RUN apt update && apt install -y sqlite3 curl libsqlite3-dev
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

